<a href="https://colab.research.google.com/github/akcterp/Scaler_DataScience/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5]
print([i**2 for i in a])

[1, 4, 9, 16, 25]


In [4]:
# we can create numpy arrays using np.array
b=np.array([1,2,3,4,5])
print(b**2)

[ 1  4  9 16 25]


In [5]:
# numpy supports elementwise operations
print(b+2)

[3 4 5 6 7]


In [6]:
c=np.array(a)
print(c)

[1 2 3 4 5]


In [7]:
# type of the entire Numpy array
type(a)

list

In [8]:
type(b)

numpy.ndarray

In [9]:
l=range(10000)


In [10]:
%timeit [i**2 for i in l]

100 loops, best of 5: 2.82 ms per loop


In [11]:
m=np.arange(10000)
print(m)

[   0    1    2 ... 9997 9998 9999]


In [12]:
%timeit m**2

The slowest run took 15.81 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 6.4 µs per loop


In [13]:
c=np.array([1,2,3])
print(type(c))
# data type of elements of the numpy array
c.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [14]:
# because of one element 4.5 , every element's dtype has been type casted into float
c=np.array([1,2,3,4.5])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1.  2.  3.  4.5]


dtype('float64')

In [15]:
# because of one element 4.5 , every element's dtype has been type casted into string
c=np.array([1,2,3,"c"])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' 'c']


dtype('<U21')

In [16]:
c=np.array([1,2,3,"4.5",3.9])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' '4.5' '3.9']


dtype('<U32')

In [17]:
# booleans are treated as 1 and 0 for True and False respectively
c=np.array([1,1,0,True,False])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1 1 0 1 0]


dtype('int64')

In [18]:
b=np.array([1,2,3,4,5])
# used to find out the dimension of the array
b.ndim

1

In [19]:
# used to find out the shape of the numpy array
b.shape

(5,)

In [20]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [21]:
# range function generates numbers for start to end(excluded) with some step size
# range( start, stop,step_size)
f=range(0,10,1)
print(f)

range(0, 10)


In [22]:
# arange function in numpy generates numbers for start to end(excluded) with some step size
# arange( start, stop,step_size)
# arange is different from range --> we can give floats as step size
g=np.arange(0,10,0.67)
print(g)

[0.   0.67 1.34 2.01 2.68 3.35 4.02 4.69 5.36 6.03 6.7  7.37 8.04 8.71
 9.38]


In [24]:
# linspace is used to create equally spaced numbers between start and end both included.
start,end,flag_count=0,100,25
np.linspace(start,end,flag_count)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [26]:
f=np.linspace(0,10,4)
f

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [27]:
# creating a 2d numpy Array
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
m.shape

(2, 3)

In [29]:
m.ndim

2

In [30]:
a = np.array([1,2,3,4,5,6,7,8])
len(a)

8

In [ ]:
len(m)

2

In [31]:
m2=np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
m2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
# here we knew that we want 2 rows, but not the columns, so we passed -1 as the parameter. 
# numpy will automatically find out the required number of columns it need to display the data.
m2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
m2.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# we need to pass atleast one dimension
m2.reshape(-1,-1)

ValueError: ignored

In [37]:
m2.reshape(5,-1)

ValueError: ignored

In [38]:
m2=np.arange(1,13)
#reshape functions reshapes the arrays into the shape of (rows and columns) we define
m2=m2.reshape(3,4)


In [39]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [41]:
m3.reshape(3,4)

ValueError: ignored

In [42]:
m4=np.array([[1,2,3],[4,5,6,8,0,9]])
m4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([4, 5, 6, 8, 0, 9])], dtype=object)

In [43]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [44]:
m3.reshape(1,13)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [45]:
m3.reshape(13,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [ ]:
m3.reshape(2,-1)

ValueError: cannot reshape array of size 13 into shape (2,newaxis)

In [46]:

a = np.arange(1,17).reshape(-1,2)
a.shape

(8, 2)

In [47]:
a = np.arange(1,17).reshape(-1,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [48]:
m4=np.arange(1,7)
m4

array([1, 2, 3, 4, 5, 6])

In [49]:
m5=m4.reshape(2,3)
print(m5)

[[1 2 3]
 [4 5 6]]


In [50]:
m5.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
m4=np.arange(1,13).reshape(6,2)
print(m4)
# .T creates a transpose of a matrix rows--> columns, columns--> rows
# converting rows into columns.
m4.T

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [52]:
m5=np.arange(3).reshape(1,3)
m5.ndim

2

In [53]:
m5.shape

(1, 3)

In [54]:
m5.T.shape

(3, 1)

In [55]:
m6=np.array([1,2,3])
m6.shape

(3,)

In [56]:
m6.ndim

1

In [57]:
m6.T

array([1, 2, 3])

In [ ]:
m6=np.array([[1,2,3]])
m6.shape

(1, 3)

In [58]:
m6.ndim

1

In [59]:
m6.T

array([1, 2, 3])

In [60]:
m7=np.arange(1,13).reshape(3,4)
m7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
m7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# creating special arrays

In [62]:
# creating 1D array with all the values as 0
np.zeros(3)

array([0., 0., 0.])

In [63]:
# creating 2D array  of shape (3,3) with all the values as 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
# creating 2D array  of shape (3,) with all the values as 1

np.ones(3)

array([1., 1., 1.])

In [66]:
# creating 2D array  of shape (6,2) with all the values as 1
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [69]:
a*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [70]:
a=np.ones((3,3),dtype=np.int32)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [71]:
# creating 2D array  of shape (3,3) with all the values as 4.0
np.full((3,3),4.0)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [72]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1,2,3 and rest as 0
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [75]:
#indexing

In [76]:
m1=np.arange(3,10)
m1

array([3, 4, 5, 6, 7, 8, 9])

In [77]:
#accessing the data
m1[0]

3

In [78]:
m1[1]

4

In [79]:
# we can access using negative indexes
m1[-1]

9

In [80]:
m1[-2]

8

In [81]:
m1[-7]

3

In [82]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
# method - 1, for accessing elements
m2[1][1]

6

In [84]:
# method - 2, for accessing elements ( Preferred )
m2[1,1]

6

In [85]:
m7=np.array([100,100,300,400,500,600])
m7

array([100, 100, 300, 400, 500, 600])

In [86]:
# We can pass a list of indexes of the elements we want to access 
m7[[2,4,5,4]]

array([300, 500, 600, 500])

In [87]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
# to access multiple elements, we need to pass the row and column indexes separately in lists.
m2[[1,1,2],[1,3,3]]

array([ 6,  8, 12])

In [89]:
# we cannot pass each elements separately.
# m2[[1,1],[1,3],[2,3]]

In [90]:
m8=np.arange(1,13)

In [91]:
m8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
# slicing elements from a numpy array.
m8[:5]

array([1, 2, 3, 4, 5])

In [93]:
m8[7:]

array([ 8,  9, 10, 11, 12])

In [94]:
# slicing elements from a numpy array using step size
m8[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [95]:
m8[1::3]

array([ 2,  5,  8, 11])

In [ ]:
# we can pass negative step sizes as well
m8[-11:-5]

array([2, 3, 4, 5, 6, 7])

In [ ]:
m8[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
m8[2:5:-1]

array([], dtype=int64)

In [ ]:
m8[5:2:-1]

array([6, 5, 4])

In [ ]:
m9=np.arange(1,13).reshape(3,4)

In [ ]:
m9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m9[0]

array([1, 2, 3, 4])

In [ ]:
m9[0][1:3]

array([2, 3])

In [ ]:
# accessing 0th indexed row and columns of indexes 1 and 2
m9[0,1:3]

array([2, 3])

In [ ]:

# slicing multiple rows and columns
m9[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
m9[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
m9[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
# if we want to access specific columns of rows, we pass the index within a list or tuple. both works
# m9[:,[0,1,2]] it also works the same way

m9[:,(0,1,2)]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2 : ] = b[ : : -1]


In [ ]:
a = [1,2,3,4,5]

In [ ]:
b = [8,7,6]

In [ ]:
a[2 : ] = b[ : : -1]

In [ ]:
a

[1, 2, 6, 7, 8]

In [ ]:
a[3]=100

In [ ]:
a

[1, 2, 6, 100, 8]

In [ ]:
m1 = np.array([[0,1,2,3],
[4,5,6,7],
[8,9,10,11]])

m1[0,1:3]

array([1, 2])

In [ ]:
a = np.array([0,1,2,3,4,5])
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
m1=np.arange(1,13).reshape(3,4)
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# numpy also supports elements logical operations.
# here we are creating mask of boolean values.
mask=m1<6
mask

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
m1[mask]

array([1, 2, 3, 4, 5])

In [ ]:
# filtering out the values that satisfies the condition or the values where we have True as value.
m1[m1%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# creating multiple conditions.
mask=(m1%2==0)|(m1%5==0) 

In [ ]:
mask

array([[False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
m1[mask]

array([ 2,  4,  5,  6,  8, 10, 12])

In [ ]:
m1%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
m1%5==0

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
mask
a[mask] = -1
# What'll be the values of a?

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
np.eye?

In [ ]:
np.eye(10,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])