In [ ]:
class Person:
  def __init__(self, Adam):
    self.name = Adam              #x
  def get_person_name(self):
    return self.name
p1=Person("Vishal")

In [ ]:
p1.name

'Vishal'

In [ ]:
p1.get_person_name()

'Vishal'

In [ ]:
Person.__init__

<function __main__.Person.__init__>

In [ ]:
class People():
    def __init__(self, name):
        self.name = name

    def get_name(self):
        print(self.name)

person1 = People("John")
person2 = People("Mary")
person1.get_name()

John


In [ ]:
class football:
    final_res= 'lose'
    def __init__(self,name,score):
        self.name = name
        self.score = score
        self.final_res = 'lose'
    
    def calc(self, winning_score):
        if self.score>winning_score:
            self.final_res='win'
match = football('Juventus',3)
match.calc(2)
print(football.final_res, match.final_res)

lose win


In [ ]:
class Student:
  # Class variable
  subject_name = 'Math for Machine Learning'

  # constructor
  def __init__(self, name, roll_no):
    self.name = name
    self.roll_no = roll_no


  # create Objects
s1 = Student('Emma', 10)
Student.subject_name = 'Machine Learning'

print(s1.name, s1.roll_no, s1.subject_name)

Emma 10 Machine Learning


In [ ]:
class solution:
  def initial(self,sets):
    return self.final(sets)
 
  def final(self, sets):
    return list(map(lambda x: ((x**3)%2==0,x**3),sets))

print(solution().initial([4,5,6]))

[(True, 64), (False, 125), (True, 216)]


In [ ]:
class Employee:

    def __init__(self, name, val):

        self.__name=name

        self.__salary=val

e1=Employee("Rahul",200)

print(e1.__salary)

AttributeError: ignored

In [ ]:
class Employee:

    def __init__(self, name, val):

        self._name=name

        self._salary=val

e1=Employee("Rahul",200)

print(e1._salary)

200


In [ ]:
class Employee:

    def __init__(self, name, val):

        self._name=name

        self._salary=val

e1=Employee("Rahul",200)

print(e1.salary)

AttributeError: ignored

In [ ]:
def bsort(a):
    n = []
    for i in a:
      n.append(min(a))
      a.pop(min(a))
      print(n)

    return n

In [ ]:
bsort([3,2,5,1])

[1]
[1, 1]


[1, 1]

In [ ]:
a = [3,2,5]
a.pop(min(a))

5

In [ ]:
arr = [5,4,3,2,1]

In [ ]:
for j in range(len(arr)-1,-1,-1):
  for k in range(0,j):
    if(arr[k]>arr[k+1]):
      temp=arr[k]
      arr[k]=arr[k+1]
      arr[k+1]=temp

In [ ]:
arr

[1, 2, 3, 4, 5]

In [ ]:
arr[-1]

5

In [ ]:
n=50
a = 0
i = n
count = 0
while (i > 0):
  a += i
  i /= 2
  count += 1
print(count)

1081


In [ ]:
print(a)

100.0


In [ ]:
def insertionSort(arr,k):
    """
    arr is the list and k is the iteration number
    store the result with variable name res
    """
    #YOUR CODE GOES HERE
    count = 0
    value=0
    for i in range(1,len(arr)+1):
        count += 1
        if count == k:
            break
        value=arr[i-1]
        j=i-1
        while (j > 0) and (arr[j-1] > value):
             #Fill the blank
            arr[j]=arr[j-1]
            j=j-1
            arr[j]=value
    print(arr)
    return arr[len(arr)//2]

In [ ]:
insertionSort([111,123,435,23,100,101,540,1000],2)

[111, 123, 435, 23, 100, 101, 540, 1000]


100

In [ ]:
def insertionSort(arr):
  value=0
  for i in range(1,len(arr)+1):
    value=arr[i-1]
    print(value)
    j=i-1
    print(j)
    while (j > 0) and (arr[j-1] > value): #Fill the blank
      arr[j]=arr[j-1]
      j=j-1
    arr[j]=value
  return arr 

In [ ]:
insertionSort([5,4,3,2,10])

5
0
4
1
3
2
2
3
10
4


[2, 3, 4, 5, 10]

In [ ]:
iest([5,4,3,2,1])

0
1
2
3


[1, 2, 3, 4, 5]

In [ ]:
def insertions(arr):

  for i in range(1,len(arr)):

    insert = i
    j = i-1

    while j>=0:
      if arr[j] < arr[i]:
        break

      a[insert],a[j] = 

In [ ]:
def insertionSort(a,k):
    """
    arr is the list and k is the iteration number
    store the result with variable name res
    """
    #YOUR CODE GOES HERE
    
    count = 0
    for i in range(1,len(a)):
        if count == k:
          break
        insert = i
        j = i-1

        while j>=0:
            if a[j]<a[insert]:
                break
            
            a[j],a[insert] = a[insert],a[j]
            insert = j
            j -= 1
        
        print(a)
    return a[len(a)//2]

In [ ]:
insertionSort([12,4,5,7,1,32,34],4)

[4, 12, 5, 7, 1, 32, 34]
[4, 5, 12, 7, 1, 32, 34]
[4, 5, 7, 12, 1, 32, 34]
[1, 4, 5, 7, 12, 32, 34]
[1, 4, 5, 7, 12, 32, 34]
[1, 4, 5, 7, 12, 32, 34]


7

In [ ]:
def iest(arr):

  for i in range(1,len(arr)):
    insert = i
    j = i-1
    print(j)
    
    while j>=0:
      if arr[j] < arr[insert]:
        break
      
      arr[j] , arr[insert] = arr[insert], arr[j]
      
      insert = j
      j -= 1
  
  return arr

In [ ]:
def isort(arr):

  for i in range(1,len(arr)):

    j = i-1
    toinsert = i

    while j >= 0:

      if arr[j] < arr[toinsert]:
        break
      
      arr[toinsert] , arr[j] = arr[j] , arr[toinsert]

      toinsert = j
      j -= 1

  return arr

In [ ]:
isort([50,5,1,60,4,3,2,0,5])

[0, 1, 2, 3, 4, 5, 5, 50, 60]

In [ ]:
def selsort(arr):

  for i in range(len(arr)-1):

    current_min = arr[i]
    

    for j in range(i+1,len(arr)) :
      if arr[j] < current_min:
        print(arr[j],current_min)
        arr[i],arr[j] = arr[j], arr[i]

      

  return arr

In [ ]:
selsort([5,4,3,2,1,50])

4 5
3 5
2 5
1 5
4 5
3 5
2 5
4 5
3 5
4 5


[1, 2, 3, 4, 5, 50]

In [ ]:
a = [1,2,3,4]
a = a[2:]+[a[1]]
a

[3, 4, 2]

In [ ]:
def solve(arr):
  result = []
  if len(arr) == 1:
    return arr[0]
  result.append(arr[0])
  arr = arr[2:].append(arr[1])
  
  return result + [solve(arr)]

In [ ]:
solve([1,2,3,4,5])

TypeError: ignored

In [ ]:
l = [ ]
def convert(b):
  if(b==0):
    return l
  digit=b%2
  l.append(digit)
  print(l)
  convert(b//2)

convert(6)
l.reverse()
for i in l:
  print(i,end="")

[0]
[0, 1]
[0, 1, 1]
110

In [ ]:
def count_freq(x, y):
  if(y!=1):
    if(x!=1):
      print("*")
      count_freq(x/2,y)
    else:
      print("#")
      y=y-1
      count_freq(x,y)

In [ ]:
count_freq(256,4)

*
*
*
*
*
*
*
*
#
#
#


In [ ]:
def fun(n):
  if (n > 50):
    return n - 5
  return fun(fun(n+11))
print(fun(45))

46


In [ ]:
def fun(i,j):
  if(i==0):
    return j
  else:
    return fun(j,i-5)

print(fun(15,8))

-7


In [ ]:
def mergeSort(lis):
    
    #YOUR CODE GOES HERE
    if len(lis) <= 1:
        return lis
    
    i,j = 0, 0
    n = len(lis)

    left = lis[:n//2]
    right = lis[n//2:]

    result = []

    while i<len(left) and j<len(right):

        if left[i]<+right[j]:
            result.append(left[i])
            i+=1
        else:
            result.append(right[j])
            j+=1
    
    if i<len(left):
        result += left[i:]
    elif j<len(right):
        result += right[j:]
    print(result)
    return result

def nth_max(lis, k):
    '''lis -> list of integers
       k -> integer'''
    
    ans=-1
    
    #YOUR CODE GOES HERE
    lists = mergeSort(lis)
    
    return lists[-k]

In [ ]:
nth_max([3,4,2,5,1,5,6,2,3,5],5)

[3, 4, 2, 5, 5, 1, 6, 2, 3, 5]


1

In [ ]:
s1 = "Akshay"
s1 = list(s1.lower())

In [ ]:
s1.count("a")

2

In [ ]:
s1 = 1234

In [ ]:
s1%10

4

In [ ]:
s1//10

123

In [ ]:
def power_of_3(n):
    '''
    input:
    n -> an integer
    output:
    True or False -> depending on whether the number is power of n or not
    '''
    
    # Your code starts here
    sumi = 0
    
    while n>=0:
        sumi += n%10
        n = n//10
    return sumi
   
    # Your code ends here

In [ ]:
1234//10

123

In [ ]:
123//10

12

In [ ]:
12//10

1

In [ ]:
1//10

0

In [ ]:
def power_of_3(n):
    '''
    input:
    n -> an integer
    output:
    True or False -> depending on whether the number is power of n or not
    '''
    if n%3 == 0:
        return True
    else: return False
    # Your code starts here
    
    # Your code ends here

In [ ]:
power_of_3(26761)

False

In [ ]:
for i in range(int(input())):
  n = int(input())
  power_of_3(n)

3
20
21
22


In [ ]:
3**1

3

In [ ]:
3**2

9

In [ ]:
def sentinelSearch(ar,target,n):
  last = ar[n-1]
  ar[n-1] = target
  i = 0
  while ar[i]!=target:
    i+=1
  ar[n-1] = last
  if (i<n-1) or target==ar[n-1]:
    return i
  else:
    return -1

In [ ]:
sentinelSearch([1,2,3,4,5],5,5) 

4

In [ ]:
def recur_search(key, values, lower, upper):
  if (upper < lower):
    return False

  mid = (lower + upper) // 2

  if (key == values[mid]):
    return True;
 
  elif (key < values[mid]):
    recur_search(key, values, lower, mid - 1)

  else: 
    recur_search(key, values, mid + 1, upper)

  return False

In [ ]:
recur_search(1, [1, 2, 3, 4, 5], 0, 4) 

False

In [ ]:
recur_search(5, [1, 2, 3, 4, 5], 0, 4)

False

In [ ]:
recur_search(3, [1, 2, 3, 4, 5], 0, 4)

True

In [ ]:
recur_search(5, [1, 2, 3, 4, 5], 0, 4) 

False

In [ ]:
a = [1,2,3]
list(enumerate(a))

[(0, 1), (1, 2), (2, 3)]

In [ ]:
def solve(A, B):
  result = 0
  for i in A:
    if B <= i:
      print(i)
      result+=1
  return result

In [ ]:
solve([1,2,3,4,4,5],4)

4
4
5


3

In [ ]:
a = [1,2,3,4]

In [ ]:
1 not in a

False

In [ ]:
6 not in a

True

In [ ]:
n = 637534208

In [ ]:
b = format(n,'b')
b

'100110000000000000000000000000'

In [ ]:
b = b[::-1]
b

'000000000000000000000000011001'

In [ ]:
int(b,2)

25

In [ ]:
def reverseBits(n):
    """
    n is integer as argument to the function
    """
    binary = format(n,'b')
    rev_bin = binary[::-1]
    result = int(rev_bin,2)
    #YOUR CODE GOES HERE
    return result

In [ ]:
reverseBits(100)

19

In [ ]:
int(b,2)

10

In [ ]:
b = format(n,'b')
b

'1010'

In [ ]:
r = b[::-1]
r = r[:len(r)-1]

In [ ]:
int(r,2)

19

In [ ]:
def showbits(n):
  #YOUR CODE GOES HERE
  b = format(n,'b')
  zero = "000000000000"
  b = b[:17]
  return zero+b

In [ ]:
showbits(10)

'0000000000001010'

In [ ]:
def count_set_bits(n):
     
    # initialize the set_bits_counter
    #count set value till n
    count = 0
    for i in range(n):
        b = str(format(i,'b'))
        count += b.count('1')
    return count

In [ ]:
count_set_bits(1)

0

In [ ]:
class DSML():

    def __init__(self, value):
        self.value = value

    def __and__(self, obj):
      mask = ~(1 << obj.value)
      self.value = self.value & mask
      return self.value & obj.value

    def __or__(self, obj):
      mask = 1 << obj.value
      self.value = self.value ^ mask
      return self.value | obj.value

    def __invert__(self):
      mask = 1 << 5
      return ~(mask | self.value)

a = DSML(8)
b = DSML(5)
c = DSML(0)
print(a & b,a | b, ~c)

0 45 -33


In [ ]:
i=13
for j in range(0,4):
  k=i>>j
  print(k,bin(k), end=" ")

13 0b1101 6 0b110 3 0b11 1 0b1 

In [ ]:
import numpy as np
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [ ]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [ ]:
list(map(lambda x:x+1, A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [ ]:
A+1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [ ]:
A+["1"]

UFuncTypeError: ignored

In [ ]:
np.arange?

In [ ]:
import numpy as np
a = np.array([[7,3,1,5,1],[1,1,11,3,5],[9,3,3,5,1],[1,5,7,3,2],[1,1,1,9,1]])
a

array([[ 7,  3,  1,  5,  1],
       [ 1,  1, 11,  3,  5],
       [ 9,  3,  3,  5,  1],
       [ 1,  5,  7,  3,  2],
       [ 1,  1,  1,  9,  1]])

In [ ]:
ev = a[a%2==0][0]
ev

2

In [ ]:
[[ev]]

[[2]]

In [ ]:
import math

In [ ]:
math.sqrt(9)

3.0

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [ ]:
import numpy as np

In [ ]:
birds = np.array(birds)

In [ ]:
np.where(birds == "Cranes")


(array([5, 8]),)

In [ ]:
import numpy as np
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(arr)

In [ ]:
mask = (arr%2==0) & (arr>3)

In [ ]:
mask

array([False, False, False, False,  True, False,  True, False,  True])

In [ ]:
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

ValueError: ignored

In [ ]:
np.sort?


In [ ]:
a = [[1],
[3, 3] ,
[5, 3, 9],
[2, 1, 4],
[7, 6 ,8]]

In [ ]:
a = np.array([a])
a

array([[list([1]), list([3, 3]), list([5, 3, 9]), list([2, 1, 4]),
        list([7, 6, 8])]], dtype=object)

In [ ]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 

In [ ]:
len(arr1)

6

In [ ]:
for i in range(len(arr1)): 

    arr3[i] = arr1[i] * arr2[i] 

In [ ]:
arr3 = arr1*arr2 

In [ ]:
for i in range(len(arr1)): 

    if(arr1[i] < 0 ): 

        arr1[i] = -1 

    else: 

        arr1[i] = 1

In [ ]:
np.where(arr1 > 0, 1, -1) 

array([1, 1, 1, 1, 1, 1])

In [ ]:
arr = np.arange(16).reshape(4,4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
arr = np.arange(10)
np.split(arr, 3)

ValueError: ignored

In [ ]:
np.split?

In [ ]:
a = [
[1],
[2]]

In [ ]:
a.shape[0]

2

In [ ]:
a = np.array(a)
a

array([[1],
       [2]])

In [ ]:
r = [np.zeros(a.shape[0],int)]
c = np.transpose(r)
c

array([[0],
       [0]])

In [ ]:
a = np.hstack((a,c))
a = np.hstack((c,a))

In [ ]:
a

array([[0, 1, 0],
       [0, 2, 0]])

In [ ]:
len(a[0])

3

In [ ]:
rn = [np.zeros(a.shape[1],int)]
rn

[array([0, 0, 0])]

In [ ]:
a = np.vstack((rn,a))
a = np.vstack((a,rn))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [0, 0, 0]])

In [ ]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [ ]:
B = np.array([[1],[2]])
B

array([[1],
       [2]])

In [ ]:
C = np.array([[1,2,3],[4,5,6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((C.T, A.reshape(3,1)), axis = 1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [ ]:
a = [1,2,3,4,5]

In [ ]:
import numpy as np
a = np.array(a)

In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)


46

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [ ]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])


arr1= 2
def func(x,y):
  return x*y
vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
import numpy as np
X = np.arange(12).reshape((3, 4))


In [ ]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = np.array([0, 1, 2])


In [ ]:
row

array([0, 1, 2])

In [ ]:
mask = np.array([1, 0, 1, 0], dtype=bool)
mask

array([ True, False,  True, False])

In [ ]:
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
a=np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])
b = [255,0,255]
c = np.all(a==b,axis=1)
print(c) 

[[False  True False]
 [False False False]]


In [26]:
s = "How much wood would a woodchuck chuck if a woodchuck could chuck wood"

In [27]:
import numpy as np
import pandas as p

a = s.split(" ")
a = list(set(a))


In [28]:
a

['wood', 'How', 'woodchuck', 'a', 'chuck', 'could', 'would', 'if', 'much']

In [29]:
count =[]
for i in a:
  count.append(s.count(i))


In [30]:
count

[4, 1, 2, 2, 4, 1, 1, 1, 1]

In [33]:
s = {'Name':["Sam","Mark","Client",'Sam','Tiger','Sam'],'employment_type':['fte','fte','intern','fte','freelancer','fte'],'department':['people','marketing','marketing','tech','marketing','tech'],'p_id':[1,2,3,4,5,6]}


In [39]:
import pandas as pd
df = pd.DataFrame(s)
df

Name employment_type department  p_id
0     Sam             fte     people     1
1    Mark             fte  marketing     2
2  Client          intern  marketing     3
3     Sam             fte       tech     4
4   Tiger      freelancer  marketing     5
5     Sam             fte       tech     6

In [49]:
ind = df[df["Name"]=="Mark"].index.tolist()
ind

[1]

In [50]:
df.drop(ind, inplace = True)

In [51]:
df

Name employment_type department  p_id
0     Sam             fte     people     1
2  Client          intern  marketing     3
3     Sam             fte       tech     4
4   Tiger      freelancer  marketing     5
5     Sam             fte       tech     6

In [57]:
df.drop("p_id",axis=1)

Name employment_type department
0     Sam             fte     people
2  Client          intern  marketing
3     Sam             fte       tech
4   Tiger      freelancer  marketing
5     Sam             fte       tech

In [58]:
df.drop_duplicates(subset="Name", keep="last", inplace=False)

Name employment_type department  p_id
2  Client          intern  marketing     3
4   Tiger      freelancer  marketing     5
5     Sam             fte       tech     6

In [59]:
a = [['Afghanistan', 1952, 8425333, 'Asia'],['Australia', 1957, 9712569, 'Oceania'],['Brazil', 1962, 76039390, 'Americas'],['China', 1957, 637408000, 'Asia'],['France', 1957, 44310863, 'Europe'],['India', 1952, 3.72e+08, 'Asia'],['United States', 1957, 171984000, 'Americas']]

In [61]:
s = pd.DataFrame(a)
s

0     1            2         3
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [63]:
s[s[2]>10000000]

0     1            2         3
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [64]:
import pandas as pd
df = pd.DataFrame({'dates':["2015-12-06", "2011-12-27", "2015-09-07", "2012-12-21", "2020-02-13"], 'RID':[498, 721, 375, 464, 813], 'Phy':[22, 45, 1, 65, 22], 'Chem':[52, 56, 32, 50, 24], 'Math':[63, 37, 68, 62, 43]}) 

In [65]:
df

dates  RID  Phy  Chem  Math
0  2015-12-06  498   22    52    63
1  2011-12-27  721   45    56    37
2  2015-09-07  375    1    32    68
3  2012-12-21  464   65    50    62
4  2020-02-13  813   22    24    43

In [68]:
filtered_df = df[df["dates"]>="2014-05-01"]
filtered_df

dates  RID  Phy  Chem  Math
0  2015-12-06  498   22    52    63
2  2015-09-07  375    1    32    68
4  2020-02-13  813   22    24    43

In [69]:
filtered_df["avg"] = np.round((df.Phy+df.Chem+df.Math)/3,2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [100]:
filtered_df

dates  RID  Phy  Chem  Math    avg
0  2015-12-06  498   22    52    63  45.67
2  2015-09-07  375    1    32    68  33.67
4  2020-02-13  813   22    24    43  29.67

In [102]:
yo =['1','2','3']

In [103]:
filtered_df['yo']=yo

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [104]:
filtered_df

dates  RID  Phy  Chem  Math    avg yo
0  2015-12-06  498   22    52    63  45.67  1
2  2015-09-07  375    1    32    68  33.67  2
4  2020-02-13  813   22    24    43  29.67  3

In [106]:
filtered_df.insert(3, "yoo", yo)

In [107]:
filtered_df

dates  RID  Phy yoo  Chem  Math    avg yo
0  2015-12-06  498   22   1    52    63  45.67  1
2  2015-09-07  375    1   2    32    68  33.67  2
4  2020-02-13  813   22   3    24    43  29.67  3

In [117]:
filtered_df.T

0           2           4
dates  2015-12-06  2015-09-07  2020-02-13
RID           498         375         813
Phy            22           1          22
yoo             1           2           3
Chem           52          32          24
Math           63          68          43
avg         45.67       33.67       29.67
yo              1           2           3
yooo            1           2           3

In [108]:
filtered_df.insert(8, "yooo", yo)

In [109]:
filtered_df

dates  RID  Phy yoo  Chem  Math    avg yo yooo
0  2015-12-06  498   22   1    52    63  45.67  1    1
2  2015-09-07  375    1   2    32    68  33.67  2    2
4  2020-02-13  813   22   3    24    43  29.67  3    3

In [116]:
filtered_df.iloc[0:2,1:3]

RID  Phy
0  498   22
2  375    1

In [111]:
filtered_df['Phy']

0    22
2     1
4    22
Name: Phy, dtype: int64

In [71]:
res_df = filtered_df.sort_values(by = ['avg'])

In [78]:
res_df.loc[:,"RID"]

4    813
2    375
0    498
Name: RID, dtype: int64

In [93]:
s = "The king has to meet the king of other state with the queen"

In [96]:
 res = list(set(s.split(" ")))
 res

['The',
 'king',
 'state',
 'other',
 'the',
 'with',
 'queen',
 'to',
 'has',
 'of',
 'meet']

In [99]:
for i in res:
  print(s.count(i))

1
2
1
1
3
1
1
1
1
1
1


In [87]:
pd.Series(res,index=res).sort_index()

The        The
has        has
king      king
meet      meet
of          of
other    other
queen    queen
state    state
the        the
to          to
with      with
dtype: object

In [118]:
df = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"])

ValueError: ignored

In [119]:
df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])

In [120]:
df = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])

ValueError: ignored

In [123]:
df = pd.DataFrame([1, "Ram", "IT"],[1, "Ram", "IT"],[1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])

TypeError: ignored

In [124]:
df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

In [1]:
s = "you are you are is the the "

In [6]:
import pandas as pd
pd.Series(s.split(" ")).value_counts().sort_index()

       1
are    2
is     1
the    2
you    2
dtype: int64

In [133]:
freq = []
words = []
for i in s.split(" "):
  words.append(i)
  freq.

you
are
you
are
is
the
the



In [1]:
import numpy as np

In [5]:
a = ["He","is","a","bastard","He"]

In [6]:
a.unique()

AttributeError: ignored

In [58]:
import pandas as pd  
df1 = pd.DataFrame({'chem_score':[10, 9, 8, 7], 'phy_score':[7, 8, 9, 10], 'Hindi_score':[9, 9, 9, 9]}, index = ['tobey', 'peter', 'chris', 'pratt'])  
df2 = pd.DataFrame({'chem_score':[10, 10, 10], 'maths_score':[6, 6, 7], 'eng_score':[9, 10, 10]}, index = ['chris', 'pratt', 'andrew'])

In [59]:
df1

chem_score  phy_score  Hindi_score
tobey          10          7            9
peter           9          8            9
chris           8          9            9
pratt           7         10            9

In [60]:
df2

chem_score  maths_score  eng_score
chris           10            6          9
pratt           10            6         10
andrew          10            7         10

In [61]:
pd.merge(df1,df2)

chem_score  phy_score  Hindi_score  maths_score  eng_score
0          10          7            9            6          9
1          10          7            9            6         10
2          10          7            9            7         10

In [40]:
value1 = np.mean([df1["chem_score"],df2['chem_score']])

In [46]:
df3['mean_rows'] = df3.mean(axis = 1)
df3

chem_score  phy_score  Hindi_score  chem_score  maths_score  eng_score  \
chris           8          9            9          10            6          9   
pratt           7         10            9          10            6         10   

       mean_rows  
chris   8.500000  
pratt   8.666667

In [48]:
df3["mean_rows"].to_list()

[8.5, 8.666666666666666]

In [4]:
 df3 = pd.concat([df1,df2],join = "inner",axis = 1)
 df3

chem_score  phy_score  Hindi_score  chem_score  maths_score  eng_score
chris           8          9            9          10            6          9
pratt           7         10            9          10            6         10

In [30]:
import numpy as np
np.mean([df1["chem_score"],df2['chem_score']])

9.125

In [34]:
list(set(df3.mean(axis=1)))

[8.5, 8.666666666666666]

In [62]:
import pandas as pd
student_data = pd.DataFrame({
'school_code': ['s001','s002','s003','s001','s002','s004','s001','s003'],
'class': ['V', 'V', 'VI', 'VI', 'V', 'VI','IX','X'],
'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes','Jane','Martin'],
'age': [12, 12, 13, 13, 14, 12, 15, 20],
'height': [173, 192, 186, 167, 151, 159, 140, 160],
'weight': [35, 32, 33, 30, 31, 32, 40, 50]},
 index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6','S7','S8']) 

In [63]:
student_data

school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30
S5        s002     V    Gino Mcneill   14     151      31
S6        s004    VI    David Parkes   12     159      32
S7        s001    IX            Jane   15     140      40
S8        s003     X          Martin   20     160      50

In [68]:
grouped_data = student_data.groupby(['school_code', 'class'])      

In [69]:
print((grouped_data.size())) 

school_code  class
s001         IX       1
             V        1
             VI       1
s002         V        2
s003         VI       1
             X        1
s004         VI       1
dtype: int64


In [70]:
n = 1                                                              
rows_to_drop=student_data.groupby(['school_code']).tail(n).index
result1 = student_data.drop(rows_to_drop, axis=0)
print(result1)

   school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30


In [106]:
df = pd.DataFrame({"City\tState":['Kolkata\tWest Bengal', 'Chennai\tTamil Nadu', 'Hyderabad\tTelengana', 'Bangalore\tKarnataka']})

In [107]:
df

City\tState
0  Kolkata\tWest Bengal
1   Chennai\tTamil Nadu
2  Hyderabad\tTelengana
3  Bangalore\tKarnataka

In [109]:
df[["city","state"]]=df["City\tState"].str.split("\t",expand = True,n=2)

In [110]:
df

City\tState       city        state
0  Kolkata\tWest Bengal    Kolkata  West Bengal
1   Chennai\tTamil Nadu    Chennai   Tamil Nadu
2  Hyderabad\tTelengana  Hyderabad    Telengana
3  Bangalore\tKarnataka  Bangalore    Karnataka

In [122]:
df = pd.DataFrame({"Name":['Himanshu', 'Robert', 'Karie', 'Rohan', 'John'], "Age": [19, 18, 17, 16, 15], "Percentage":[90, 20, 93, 49, 92], "Stream":['Commerce', 'Arts', 'Science', 'Commerce', 'Science']})

In [123]:
df

Name  Age  Percentage    Stream
0  Himanshu   19          90  Commerce
1    Robert   18          20      Arts
2     Karie   17          93   Science
3     Rohan   16          49  Commerce
4      John   15          92   Science

In [125]:
df = df[df["Percentage"]>=75]
df

Name  Age  Percentage    Stream
0  Himanshu   19          90  Commerce
2     Karie   17          93   Science
4      John   15          92   Science

In [126]:
df[(df["Stream"]=="Commerce") | (df["Stream"] == "Arts")]

Name  Age  Percentage    Stream
0  Himanshu   19          90  Commerce

In [143]:
df = pd.DataFrame({"a":[412,0,456,0,434,429,418],
"b":["John", "Mitra", "Ritz", "0","Anny", "Hema", "0"],
"c":[0,32,25,0,35,28,38]})

In [138]:
df.all(axis = 1)

SyntaxError: ignored

In [144]:
df[(df == 0).all(axis=1)].index

Int64Index([], dtype='int64')

In [151]:
df.drop(df[(df == 0).sum(axis=1)==2]

KeyError: ignored

In [1]:
df = pd.DataFrame{'name':["Mark","Ram","Dev","Clark"], "profession":['dev','mle','mle','sde'],"gender":['male','male','male','male'], "age":[21,20,30,25],"review":['need improvement','Can be improved','Scope of improvement','Can be improved'],"rating":[10,5,7,10]}

SyntaxError: ignored

In [2]:
import pandas as pd